from .upload import section_upload as upload
from .missing_data import section_missing_data as missing_data
from .inconsistency import section_inconsistency as inconsistency
from .outliers import section_outliers as outliers
from .duplicates import section_duplicates as duplicates
from .encoding import section_encoding as encoding
from .scaling import section_scaling as scaling
from .imbalanced import section_imbalanced as imbalanced
from .pipeline_preview import section_pipeline_preview as pipeline_preview
from .dashboard_download import section_dashboard_download as dashboard_download