[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "data_preprocessing_studio"
version = "0.1.0"
description = "Data preprocessing utilities"
dependencies = ["streamlit", "pandas", "numpy", "scipy", "altair", "regex", "openpyxl", "wordcloud"]
